turbonomic/turbo-go-sdk

pkg/mediationcontainer/client_protobuf_endpoint.go
pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/mediation_container.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/sdk_client_protocol.go
pkg/mediationcontainer/transport_endpoint.go
pkg/probe/turbo_probe.go
pkg/proto/proto_version_const.go
pkg/service/tap_service.go

- Try to connect to server websocket until connected by retrying every 30 seconds. Todo: read the connection retry interval from the config file.
- New routine that is waiting for closed/error notification from the underlying transport point and will  try websocket reconnect and perform sdk client protocol 
- Ability to stop the listener routines for the ClientWebSocketTransport and ClientProtobufEndpoint
- Ability for a TAP service to disconnect from turbo server

Add routine to reconnect to server when the server websocket is closed

---

Godeps/Godeps.json
pkg/mediationcontainer/client_protobuf_endpoint.go
pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/mediation_communication_config.go
pkg/mediationcontainer/mediation_communication_config_test.go
pkg/mediationcontainer/protobuf_endpoint.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/sdk_client_protocol.go
pkg/probe/turbo_probe.go
pkg/service/tap_service.go
vendor/github.com/turbonomic/turbo-api/pkg/client/api_client.go
vendor/github.com/turbonomic/turbo-api/pkg/client/config.go
vendor/github.com/turbonomic/turbo-api/pkg/client/request.go

One bug has also been fixed. Inside [remote_mediation_client.go -> Init()](https://github.com/turbonomic/turbo-go-sdk/compare/master...DongyiYang:logging?expand=1#diff-3cf7d015404469ef5a531d99138fda0dL110), the default case for the select would make the for loop to be an infinite loop without waiting or being block. I've deleted the default case.

Updated Logging level and Dependency to Go API

---

pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/client_websocket_transport_test.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/transport_endpoint.go

Create [status](https://github.com/turbonomic/turbo-go-sdk/compare/master...DongyiYang:ReconnectFix?expand=1#diff-ab2326914686a36993657f52e15b6884R51) field in ClientWebSocketTransport to indicate the current transport layer status.
closeAndResetWebSocket, stopListenForMessages immediately if there is an error during WebSocket receive, as reconnect gets notified everytime. Changes are [here](https://github.com/turbonomic/turbo-go-sdk/compare/master...DongyiYang:ReconnectFix?expand=1#diff-ab2326914686a36993657f52e15b6884R169).

Fix Reconnect Failure

---

pkg/builder/entity_dto_builder.go
pkg/builder/entity_dto_builder_test.go

Before the change, when an entity buys from multiple provider, only the last provider ID gets saved. This is because at [L286](https://github.com/turbonomic/turbo-go-sdk/compare/master...DongyiYang:BugFix?expand=1#diff-36bab2b1b4c72203037173c3ac876f2eL286), we reused provider while its value changed every time when iterating the map key values.
A test case has been added.

Fixed Bug When an EntityDTO Buys from Multiple Provider

---

pkg/mediationcontainer/mediation_communication_config.go
pkg/mediationcontainer/mediation_communication_config_test.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/sdk_client_protocol.go
pkg/version/proto_version_const.go

add version as one of the parameter in serverMeta. So when in use, the JSON configuration should look like the following:
```json
{
"communicationConfig": {
"serverMeta": {
"version": "5.9.0-SNAPSHOT",
"turboServer": "<server-url>"
},
"restAPIConfig": {
"opsManagerUserName": "foo",
"opsManagerPassword": "bar"
}
},
"targetConfig": {
"probeCategory":"CloudNative",
"targetType":"some_type",
"address":"http://127.0.0.1:8080",
"username":"foo_user",
"password":"bar_password"
}
}
```
If user don't provide anything there, it will use the default value, which should be the release value hard coded in version package.

Expose Version As A Parameter

---

pkg/mediationcontainer/remote_mediation_client.go
pkg/service/tap_service.go

Before the change, if there is incorrect version, go sdk generated the following log then exited the program. 
```
E0728 17:48:53.491103   70680 sdk_client_protocol.go:85] Protocol version negotiation failed%!(EXTRA string=REJECTED) :Protocol version "5.1.0-SNAPSHOT" is not allowed to communicate with server)
E0728 17:48:53.491120   70680 sdk_client_protocol.go:29] Failure during Protocol Negotiation, Registration message will not be sent
E0728 17:48:53.491131   70680 remote_mediation_client.go:135] Registration with server failed
panic: close of nil channel
goroutine 85 [running]:
github.com/turbonomic/kubeturbo/vendor/github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.(*remoteMediationClient).Stop(0xc4206d6e60)
/Users/dongyiyang/Sandbox/Go/src/github.com/turbonomic/kubeturbo/vendo …
```

Resolved Issue When Version Number is Incorrect

---

pkg/builder/replacement_entity_meta_data_builder.go
pkg/builder/replacement_entity_meta_data_builder_test.go

fix issue [Capacity gets unset while patching the commodity during stitching](https://vmturbo.atlassian.net/browse/OM-24073)
The property names is copied from `com.vmturbo.platform.sdk.common/com.vmturbo.platform.common.builders`.

set replacement commidity property

---

pkg/mediationcontainer/client_protobuf_endpoint.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/sdk_client_protocol.go
pkg/probe/probe_builder_test.go
pkg/probe/turbo_probe.go
pkg/version/proto_version_const.go

Turbo GO SDK is to be updated to be compatible and work with Turbonomic Operations Manager v6.0
Updated the version string that will be sent by the TAP services in the Negotiation message during the registration protocol.

Change server version string to 6.0.0

---

pkg/builder/registration_builder.go
pkg/builder/registration_builder_test.go
pkg/probe/probe_builder.go
pkg/probe/probe_builder_test.go
pkg/probe/probe_config.go
pkg/probe/probe_config_test.go
pkg/probe/probe_registration.go
pkg/probe/probe_registration_test.go
pkg/probe/turbo_probe.go
pkg/probe/turbo_probe_test.go
pkg/sdk_constants.go

- Restructured how the discovery metadata structure is set in the probe, making it easy to change the default intervals by the probe.
- Probe is always built with a  default discovery metadata structure.
- Added unit tests.

Drop unsupported discovery intervals from probe registration data

---

.travis.yml
Makefile

**Problems** of `.travis.yml`
1. golang version(1.7) is old;
2. no output during goverall process: travis will terminate this process if it can not see any output for a long time;
3. There are some broken ( and invisible) characters in Makefile;
**Solution**
1. update golang version to 1.9;
2. add '-v' option, and allow 'tip' failure;
3. update Makefile

fix travis

---

Makefile
pkg/mediationcontainer/sdk_client_protocol.go
pkg/mediationcontainer/sdk_client_protocol_test.go

[OM-27956](https://vmturbo.atlassian.net/browse/OM-27956)
**Problem**:
In the initial protocol handshake period, if the websocket is broken before kubeturbo can receive the `VersionNegotiation` response or the `ProbeRegistration` response via the websocket. Then Kubeturbo will be stuck there waiting for this never coming respone.
**Solution**
Add timeout when waiting for the server response.

Fix OM-27956

---

pkg/supplychain/supply_chain_node_builder.go
pkg/supplychain/supply_chain_node_builder_test.go

[OM-31364](https://vmturbo.atlassian.net/browse/OM-31364)
Add two functions to set supplyChainNodeTemplate 's **priority** and **template_type**.
**Problem**
For probe `kubeturbo`, in supplyChain definition, virtualMahcine template's **priority** is set to _0_, and **template_type** is set to _template_base_. 
In this case, when stitching with VCProbe, which has the same **priority** and  **template_type**  setting for virtualMachine, `DiscoveryContextUtil` will choose randomly one of the two template, and report an error.
**Fix**
In this go-sdk, a SetPriority function is provided. So that probe `kubeturbo` can set **priority** to smaller than _0_ (while keeping  **template_type** to _template_base_ to make the VM available in case of no stitching) .

add setPriority: able to set vm to lower priority

---

pkg/mediationcontainer/client_protobuf_endpoint.go
pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/probe/turbo_probe.go
pkg/service/tap_service.go

[OM-33820](https://vmturbo.atlassian.net/browse/OM-33820)
**Problem**
Kubeturbo cannot communicate with Tomcat server properly after Tomcat server restarts.
Based on my observation, there are two bugs in the websocket module for this problem:
1.  Concurrent write to websocket
This can cause Kubeturbo exit with panic, and not be able to send the `Close` message to Tomcat server.
2.  **_Some times_** it cannot detect that the websocket has gone.
So it will not try to reconnect to Tomcat server.
**Solution**
1. fix the concurrent write by a lock.
Every write will need to acquire the lock first. This may hurt the performance, but in kubeturbo or other probes, there won't be many writes.
Besides, this is a temporary fix. We can switch to [another …

OM-33820:  add ping and resolve concurrent write websocket

---

pkg/probe/probe_builder.go
pkg/probe/turbo_probe.go

**Problem**
1.  `ProbeBuilder`  forgot to add `entityMetadataProvider`;
2.  No error logs when `TurboProbe` cannot find the target by `targetId`;

fix add EntityMeta provider

---

pkg/mediationcontainer/discovery_response_sender.go
pkg/mediationcontainer/remote_mediation_client.go

Currently, the turbo-go-sdk can only send DiscoveryResponse of one DTO type, e.g., Entity DTOs. It will fail at server side to handle the case if there are other DTO type, e.g., Group DTO due to the server-side requirement.
This PR is to add the logic to chunk DiscoveryResponse message based on DTO types so one message chunk will be sent to server for each DTO type in the response.

Chunk DiscoveryResponse message based on DTO types.

---

pkg/builder/commodity_dto_builder.go

Currently, at server side, only VM VCPU capacity and used values are patched. However, it causes some inconsistent issue for the peak value. To avoid it, Kubeturbo needs also set peak value and patch it at server side.
This is the change at turbo-go-sdk side.

Add method to set peak value in commodity DTO builder.

---

pkg/builder/merged_entity_meta_data_builder.go

MergedEntity metadata will be used in lieu of ReplacementEntity metadata for stitching proxy entities with its real entity from another probe.
This metadata will be used by prometurbo probe in its supply chain definition.

Builder for MergedEntity metadata 

---

pkg/builder/merged_entity_meta_data_builder.go

- Edited the builder for setting up the bought commodity metadata in the merged entity builder
- Methods that are exported outside of the sdk package should start with capital letter.

Methods in merged entity metadata builder

---

pkg/service/tap_service.go

allow the probe to continue even if the rest api does not authenticated assuming the user can manually add the target when using SSO/SAML
Before the change:
```
I0613 17:03:30.857008   69808 kubeturbo.go:106] Run Kubeturbo service (GIT_COMMIT: )
I0613 17:03:30.966083   69808 mediation_container.go:52] ---------- Created MediationContainer ----------
E0613 17:03:31.009958   69808 tap_service.go:158] Cannot login to the Turbo API Client: unsuccessful Turbo server login response: 401 Unauthorized. Invalid credentials.
I0613 17:03:31.010632   69808 mediation_container.go:105] Registered Cloud Native::Kubernetes-2305542295
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cd7afb]
goroutine 1 [running]: …
```

allow the probe to continue even if the rest api does not authenticate

---

pkg/builder/group/cluster_builder.go
pkg/builder/group/cluster_builder_test.go
pkg/builder/group/constraint_group_builder.go
pkg/builder/group/group_builder.go
pkg/builder/group/policy_builder.go

This pull request add changes to the turbo-go-sdk to support building a group DTO with cluster constraint. As a result of the change, some refactoring is also done:
* Added `cluster_builder.go` to export the `ClusterBuilder`.
* Because `ClusterBuilder` is essentially an `AbstractConstraintGroupBuilder`, so I moved `AbstractConstraintGroupBuilder` out of the `policy_builder.go` file and created a `constraint_group_builder.go` for it, so it is cleaner.
* Corrected some formatting issues.
* Added test cases.

SDK change to support building group DTO with cluster constraint

---

pkg/builder/group/constraint_group_builder.go
pkg/builder/group/policy_builder.go

Currently I'm setting constraint id, name and display name all the same.

Added support to properly specify anti-affinity policies

---

pkg/service/tap_service.go

Currently when `kubeturbo` is started, it performs the following actions in the following order:
1. Log in to the Turbo server with the configured username and password, and obtain a session cookie
1. Register itself as a probe to the Turbo server, and establish a websocket connection, **retry every 30 seconds if connection fails**
1. Add a target with Turbo server using the session cookie obtained from a successful login
We observe a problem when a `kubeturbo` pod is injected with an `istio-proxy` sidecar, the login would fail. This is because the `kubeturbo` container and the `istio-proxy` container are started at the same time, and before the `istio-proxy` container is fully started, the network is not ready, that is why we are seeing the following error messages in the log:
```
E1119 …
```

Fix kubeturbo cannot log in to Turbo server when sidecar is injected

---

pkg/mediationcontainer/client_protobuf_endpoint.go
pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/protobuf_endpoint.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/sdk_client_protocol.go
pkg/probe/turbo_probe.go

There are many unmeaningful and confusing logging from `turbo-go-sdk` package, which makes the product look rather unprofessional. For example:
* We would directly print out a byte array, which sometimes produce garbage letters, and sometimes produce nothing:
```
I1017 07:19:02.967487       1 protobuf_endpoint.go:79] Parsing^@^REProtocol version "7.21.0-SNAPSHOT" is allowed to interact with server
...
```
* Unnecessary verbose logging at V(2) level, for example:
```
I1017 07:19:02.967725       1 turbo_probe.go:306] ProbeInfo probeType:"Kubernetes-1848268059" probeCategory:"Cloud Native" supplyChainDefinitionSet:<templateClass:VIRTUAL_APPLICATION templateType:BASE templatePriority:0 commodityBought:<key:<templateClass:APPLICATION providerType:LAYERED_OVER cardinalityMax:2147483647 …
```

Declutter logging

---

go.mod
go.sum
pkg/mediationcontainer/client_protobuf_endpoint.go
pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/mediation_communication_config.go
pkg/mediationcontainer/mediation_communication_config_test.go
pkg/mediationcontainer/mediation_container.go
pkg/mediationcontainer/transport_endpoint.go
pkg/probe/turbo_target_info.go
pkg/service/tap_service.go
pkg/service/turbo_communication_config.go
pkg/service/turbo_communication_config_test.go
vendor/github.com/davecgh/go-spew/LICENSE
vendor/github.com/davecgh/go-spew/spew/bypass.go
vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
vendor/github.com/davecgh/go-spew/spew/common.go
vendor/github.com/davecgh/go-spew/spew/dump.go
vendor/github.com/davecgh/go-spew/spew/format.go
vendor/github.com/stretchr/testify/LICENSE
vendor/github.com/stretchr/testify/assert/assertions.go
vendor/github.com/turbonomic/turbo-api/pkg/api/resource_type.go
vendor/github.com/turbonomic/turbo-api/pkg/api/type.go
vendor/github.com/turbonomic/turbo-api/pkg/client/api_client.go
vendor/github.com/turbonomic/turbo-api/pkg/client/client.go
vendor/github.com/turbonomic/turbo-api/pkg/client/config.go
vendor/github.com/turbonomic/turbo-api/pkg/client/request.go
vendor/github.com/turbonomic/turbo-api/pkg/client/tp_client.go
vendor/modules.txt

This PR depends on https://github.com/turbonomic/turbo-api/pull/7. 
This PR changes `turbo-go-sdk` to allow adding target through either `api` or `topology-processor` service. The following is the flow:
* The `configmap` `serverURL` should only specify the scheme (http/https), host, port, same as today. No subpath (custom URL) should be specified.
* During probe registration, try API endpoint at `serverURL/vmturbo/remoteMediation`, if successful, we know the service is an API endpoint.
* Otherwise, try TP endpoint at `serverURL/remoteMediation`, if successful, we know the service is a TP endpoint.
* If a `targetName` is defined, then add target through the proper endpoint. i.e., for TP endpoint, do `POST serverURL/target`, for API endpoint, do login first, then do `POST …

Allow adding target through either api or topology-processor service

---

pkg/mediationcontainer/remote_mediation_client.go
pkg/service/tap_service.go

Soon we are going to release `kubeturbo` that supports ARM model (i.e., 7.22.4). This version of `kubeturbo` is not compatible with older version of Turbonomic server. If the customer upgrades `kubeturbo` to 7.22.4 without upgrading the Turbonomic server (e.g., 7.22.2), he will see that `kubeturbo` panic, and in a `CrashLoopBackoff` state:
```
I0617 18:57:54.631582       1 sdk_client_protocol.go:41] Starting probe registration ....
I0617 18:57:54.631598       1 sdk_client_protocol.go:163] SdkClientProtocol] Creating Probe Info for Kubernetes-Turbonomic
E0617 18:58:24.754488       1 sdk_client_protocol.go:72] [RegistrationEndpoint]: wait for message from channel timeout(30 seconds)
E0617 18:58:24.796853       1 sdk_client_protocol.go:144] [RegistrationEndpoint] : read Registration response …
```

Allow probe to continue when registration fails

---

pkg/builder/commodity_dto_builder.go
pkg/builder/commodity_dto_builder_test.go
pkg/builder/merged_entity_meta_data_builder.go
pkg/builder/merged_entity_meta_data_builder_test.go
pkg/dataingestionframework/data/dif_conversion.go
pkg/supplychain/supply_chain_builder.go
pkg/supplychain/supply_chain_builder_test.go

This PR addresses the following issues:
* Remove the internal and external return types from merged entity metadata builder due to protocol changes
* Add conversion and validation for certain types of commodities when creating the DTOs:
* For `THREADS` and `CONNECTION`, requires capacity to be set
* For `REMAINING_GC_CAPACITY`, set the used value to be 100-used, and set the capacity to be 100
* For `DB_CACHE_HIT_RATE`, set the capacity to be 100
* Return error when used value is negative
* Validate the `chargedBy` relationship when creating supply chain nodes

Miscellaneous changes related target turbo with turbo

---

pkg/builder/commodity_dto_builder.go

This PR adds a default capacity to the Application commodity being created by both `kubeturbo` and `DIF` probe. 
For other access commodities such as `Cluster` and `VMPMAccess` commodities, `kubeturbo` already sets default capacities for them. `DIF` probe does not create other access commodities.

Add default capacity to Application commodity

---

pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/mediation_container.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/service/tap_service.go

In #101 , we modified the logic to allow probe to continue instead of exit with panic when registration fails (e.g., due to protocol incompatibility with server). Once a probe reaches this state, it will not retry registration anymore.
However, in some circumstances, we do want to retry registration when it fails. For example, when server is being upgraded (there is no protocol incompatibility issue), not all services are ready at the same time, and as a result, the probe registration may fail temporarily. We want the probe to retry registration until all services are ready, at which time the registration will succeed. If we do not retry, user has to manually restart the probe. It is rare to have protocol incompatibility between `kubeturbo` and the server, but server upgrade is more …

Gracefully shutdown mediation client when registration fails

---

pkg/dataingestionframework/data/dif_types.go

This is a simple change to add a `namespace` field to the `DIFEntity` in preparation for the change in `prometurbo` to support multi-tenant business application. This field is not needed by `turbodif`, so it is not exposed publicly in the JSON field.

Add namespace field to DIFEntity

---

pkg/dataingestionframework/data/dif_types.go
pkg/dataingestionframework/data/dif_types_test.go

https://vmturbo.atlassian.net/browse/OM-64661
Currently in `DIFEntity`, the `Metrics` is a map where the key is the metric type, and the value is an array of metric definitions:
```
type DIFEntity struct {
UID                 string                     `json:"uniqueId"`
Type                string                     `json:"type"`
Name                string                     `json:"name"`
HostedOn            *DIFHostedOn               `json:"hostedOn"`
MatchingIdentifiers *DIFMatchingIdentifiers    `json:"matchIdentifiers"`
PartOf              []*DIFPartOf               `json:"partOf"`
Metrics             map[string][]*DIFMetricVal `json:"metrics"`
namespace           string
partOfSet           set.Set
hostTypeSet         set.Set
}
```
We did not properly specify the use case for the …

Properly support multiple keys for the same type of commodity

---

pkg/mediationcontainer/remote_mediation_client.go

We consistently get a panic at kubeturbo exit:
```
I1123 08:50:02.533964       1 kubeturbo_builder.go:363] Kubeturbo service is stopped.
I1123 08:50:02.534010       1 remote_mediation_client.go:157] [Init] Exit routine *************
panic: close of closed channel
goroutine 681 [running]:
github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.(*remoteMediationClient).Init(0xc00030cf60, 0xc00020fb90, 0xc0005a7b60)
/Users/irfanurrehman/pkg/mod/github.com/turbonomic/turbo-go-sdk@v0.0.0-20201030102636-d9a5135b441d/pkg/mediationcontainer/remote_mediation_client.go:158 +0x442
github.com/turbonomic/turbo-go-sdk/pkg/mediationcontainer.InitMediationContainer(0xc00020fb90, 0xc0005a7b60)
/Users/irfanurrehman/pkg/mod/github.com/turbonomic/turbo-go-sdk@v0.0.0-20201030102636-d9a5135b441d/pkg/mediation …
```

Fix channel close at exit

---

pkg/builder/commodity_dto_builder.go

One use case is to set the throttling util threshold (a.k.a. effective capacity) to be lower than 100%.

Added capability to set utilization threshold percentage.

---

pkg/service/tap_service.go

Background:
We have customer reported the following:
Looks like we got past the 401 error by changing the password to something less complex. The password was “uZ3sE161G$0&E4d5”, we changed it to “Password123” and it worked.
That password was able to be used to login to the UI just fine. Are you guys aware that the UI accepts passwords that the API doesn’t? Is this a password encapsulation issue? Seems like a bug to me.
Fix:
Escape the special Char with url.QueryEscape
Side-fix:
Removed sensitive logging

Escape the special char

---

go.mod
go.sum
pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/mediation_communication_config.go
pkg/mediationcontainer/mediation_container.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/transport_endpoint.go
pkg/service/tap_service.go
vendor/github.com/turbonomic/turbo-api/pkg/api/resource_type.go
vendor/github.com/turbonomic/turbo-api/pkg/client/api_client.go
vendor/github.com/turbonomic/turbo-api/pkg/client/client.go
vendor/github.com/turbonomic/turbo-api/pkg/client/config.go
vendor/github.com/turbonomic/turbo-api/pkg/client/request.go
vendor/github.com/turbonomic/turbo-api/pkg/client/tp_client.go
vendor/modules.txt

*** Intent
For secure probe registration, we now need to acquire the jwtToken in the header of websocket connection. The review includes the changes to use the new APIs in turbo-api in https://github.com/turbonomic/turbo-api/pull/13 and use it in websocket authentication.
Please note, we still need to update the go.mod after the api is merged.
*** Implementation
This review only includes the change for SDK. More changes in Turbo go SDK and Kubeturbo. The flow is the following:
Kubeturbo load clientid and clientsecret from k8s secret
In Turbo Go SDK, clientid and clientsecret are parsed to APIClient during the creation of the client
GetHydraToken and GetJwtToken are invoked before the websocket connection.
*** Test
Use the secure probe e
nabled server and check the probe registration.

[OM-85109]: Go SDK support for secure probe connection

---

pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/mediation_container.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/transport_endpoint.go
pkg/service/tap_service.go

Intent:
The server side has the token expiration logic to expire the jwtToken after certain interval (configurable). We need to make sure kubeturbo can refresh the jwtToken every time the websocket needs to be connected.
Implementation:
Since the websocket connection is in mediation container, and jwt Token is done through Rest API client, we decided to use separate go routine with channels in this case. See below
Test:
Tested the following scenario:
1. Probe registration with secure probe enabled, and provide client id and secret with k8s secret
2. Probe registration with secure probe disabled, without providing client id and secret
3. Re-connect by restarting TP

[OM-85592]: Refresh jwt token support

---

pkg/probe/probe_registration.go
pkg/probe/turbo_probe.go

[PR](https://github.com/turbonomic/kubeturbo/pull/730) contains updates to kubeturbo to implement the target addition interface to provide target info details during probe registration, so a target can be automatically added to the server when it is running in secure mode.
kubeturbo users need to configure `TargetIdentifier` field before deploying the kubeturbo image. If it is not configured then the target is not automatically added and the user can add target via UI. 
We need to keep the same behavior when adding auto-adding target during probe registration.
This MR contains changes in the target addition interface in turbo-go-sdk to check if the TargetIdentifier is valid before including the TargetInfo in the `ProbeInfo`.
This will ensure that a target with empty string is not …

[OM-88832]: Add TargetInfo during probe registration only with valid TargetIdentifier

---

go.mod
go.sum
pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/sdk_client_protocol.go
pkg/service/tap_service.go
pkg/service/turbo_communication_config.go
vendor/github.com/turbonomic/turbo-api/pkg/client/api_client.go
vendor/modules.txt

Need to update the turbo-api in vendor directory for turbo-go-sdk based on the changes from 
[this PR](https://github.com/turbonomic/turbo-api/pull/15).
Additionally added some logging while attempting to add probe target via API. 
Currently, this mechanism is still retained since the server can run in secure or non-secure mode.
See some examples below.
When the server runs in secure mode, and if  the probe is **able to establish a secure websocket** connection to the server , its target is also automatically registered in the server.
-  The probe (`TAPService`) will also try to add target via the API, if and only if the Turbo admin API credentials are still configured. In this case, however, since the target already exists, the API call will simply return.
- If the Turbo admin API …

[OM-90183]: Update turbo-api vendor and additional logging during target addition

---

pkg/mediationcontainer/client_websocket_transport.go

Decrease ping interval to 30 seconds.
Default load balancers will typically implement a 60 second timeout. If there is no activity detected, the connection will be closed.  This poses a potential issue in that the secure WebSocket communication created by Kubeturbo can potentially be closed due to exceeding that default timeout when our ping interval is set to the same value.
Ran Kubeturbo locally with changes and verified that pings we sent at 30 seconds intervals.
```
I1114 10:07:56.987494   46340 client_websocket_transport.go:165] begin to send Ping message
I1114 10:07:57.015493   46340 client_websocket_transport.go:335] Received pong msg
I1114 10:08:26.988483   46340 client_websocket_transport.go:165] begin to send Ping message
I1114 10:08:27.021533   46340 …
```

[OM-91918]: Decrease ping interval to 30 seconds.

---

pkg/builder/entity_dto_builder.go

Additional change required for this [PR](https://github.com/turbonomic/turbo-go-sdk/pull/144), so the ContainerSpec data is added to the EntityDTO protobuf message

[OM-93675]: Add container spec data to the entity dto 

---

pkg/mediationcontainer/client_websocket_transport.go
pkg/mediationcontainer/client_websocket_transport_test.go
pkg/mediationcontainer/mediation_communication_config.go
pkg/mediationcontainer/mediation_communication_config_test.go
pkg/mediationcontainer/remote_mediation_client.go
pkg/mediationcontainer/sdk_client_protocol.go
pkg/mediationcontainer/sdk_client_protocol_test.go
pkg/service/tap_service.go
pkg/service/turbo_communication_config.go
pkg/service/turbo_communication_config_test.go

- Increase the timeout interval when waiting for response from the server during probe registration process. Default is increased to 300 sec from 30 sec. 
- Also added an option to allow the probe pod to exit if the timeout still occurs during registration. This will allow the Kubernetes system to restart the probe. 
- The registration response wait timeout and the option to exit on timeout are made available as configuration options when configuring the TAP service.
Default Configuration options:
`I0425 21:03:11.668518       1 sdk_client_protocol.go:44] **** SDK Protocol timeout related config [&{RegistrationTimeoutSec:300 ExitOnProtocolTimeout:false}]
`
Logging time taken taken to register the probe:
`I0425 21:03:11.702456       1 sdk_client_protocol.go:136] [NegotiationEndpoint] : …

[OM-100430]: TAP service configuration option to increase timeout to complete registration with server

---

pkg/mediationcontainer/client_websocket_transport.go

kubeturbo (8.8.4) crashed when losing its connection to the cluster in Netskope early access tests.
The stack trace showing a NPE in the routine of pinging when monitoring the websocket connection:
```
I0419 20:26:12.754521       1 remote_mediation_client.go:115] [Reconnect] transport endpoint is closed, starting reconnect ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1b5e9a1]
goroutine 1262 [running]:
[github.com/gorilla/websocket.(*Conn).SetWriteDeadline(..](https://urldefense.proofpoint.com/v2/url?u=http-3A__github.com_gorilla_websocket.-28-2AConn-29.SetWriteDeadline-28..&d=DwMFaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=ChEuJySc-ouWcdrXhCMSRckTpW_l-2QwdxCR6xijptg&m=9Y_Zk0ooIh6-HdSQswb6orZZOC17oQaEFjgIbBKoH2 …
```

[OM-100967]:  add guard for NPE in websocket write method

---

pkg/mediationcontainer/discovery_response_sender.go

We updated protobuf go binding to support target level action policies in #150, we need to update the  `chunkDiscoveryResponse` function to add the new action policies as a separate chunk.
Verify in a dev environment, and make sure that the new action policies are in the SDK discovery dump from TP:
```
action_policies {
entityType: VIRTUAL_MACHINE
policyElement {
actionType: PROVISION
actionCapability: SUPPORTED
}
policyElement {
actionType: SUSPEND
actionCapability: SUPPORTED
}
}
```

[TRB-40128] Add ActionPolicies in chunked discovery response

---

pkg/builder/entity_dto_builder.go
pkg/builder/entity_dto_builder_test.go

Filter out duplicated commodities that have the same commodity type and the key from the entity DTO objects.
- Adding filter implementation to prevent appending duplicated sold commodities to the sold commodity list
- Adding logic to prevent appending existing sold commodities to the sold commodity list
- Adding logic to prevent appending existing buy commodities to the buy commodity list

[TRB-23205]: Filter out duplicate commodities
